import './global.css';

export const metadata = {
  title: 'Welcome to auth',
  description: 'Generated by create-nx-workspace',
};


type Props = {
  children: React.ReactNode;
};

export default function RootLayout({
  children
}: Props) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
